### ISSUE TITLE
Transducer composition

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/rebellion#191]
Transducers are composable and form a category. It should be possible to combine `(mapping add1)` and `(mapping (* _ 2))` into a single transducer equivalent to `(mapping (compose add1 (* _ 2))`. Proposed API surface:

```
(transducer-compose [trans transducer?] ...) -> transducer?
(transducer-pipe [trans transducer?] ...) -> transducer?
```

...where `transducer-compose` combines transducers with an order similar to how `compose` combines functions, and `transducer-pipe` is equivalent to `transducer-compose` with the list of transducers reversed. The pipe variant should be preferred, since left-to-right categorical composition is generally more readable than right-to-left composition.

**Comment by rocketnia** [comment]
I like this issue!

I bet once you have this, it'll simplify a lot of other code. So many of the existing transducers seem like they'd be built up out of combinations of `transducer-pipe`, `append-mapping`, and `folding`.

And I could really use this for #301 -- even though, ironically, performance is one likely place where transducer composition might have downsides.

**Comment by jackfirth** [comment]
It could, but I'm actually planning on _avoiding_ using it for any of the current transducers. Partly for performance, but mostly to keep dependencies simpler. I've been bitten before by over-eager use of an abstraction to implement a library's core APIs. Makes it more painful to implement and test the abstraction, since you can't use the core APIs to do that anymore. I'd rather not couple things that tightly.
