### ISSUE TITLE
Remove list->multiset

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/rebellion#252]
There's no point to using `list->multiset` over `sequence->multiset`. The latter always works wherever the former would, and it can be made just as fast by special-casing input `list?` sequences. All current uses of `list->multiset` in Rebellion should be replaced with `sequence->multiset` and the `list->multiset` function should be deleted.

**Comment by campbellr** [comment]
Hi @jackfirth , any objections to me picking up this issue?

**Comment by jackfirth** [comment]
@campbellr None at all, go for it! I'll assign it to you.

**Comment by jackfirth** [comment]
Closed by #261
