### ISSUE TITLE
Materializing transducers

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/rebellion#339]
It's tricky to test transducers with the `transduce` function alone. Consider this pipeline:

```racket
(transduce (list 1 2 3) (mapping -) #:into into-list)
```

While the `(mapping -)` transducer may seem to have only one sensible implementation, there are in fact multiple behaviors it could have without affecting the result of the pipeline:

1. It could consume and emit values one at a time (the sensible implementation), resulting in the sequence of actions `[Start, Consume(1), Emit(-1), Consume(2), Emit(-2), Consume(3), Emit(-3), Finish]`

2. It could buffer everything into memory first, and only once the upstream sequence is finished start emitting items, resulting in the sequence of actions `[Start, Consume(1), Consume(2), Consume(3), HalfClose, HalfClosedEmit(-1), HalfClosedEmit(-2), HalfClosedEmit(-3), Finish]`.

3. Various other behaviors that vary in how much buffering occurs and when consumption and emission happen relative to each other.

This is not merely an implementation detail, it's *part of the semantics* of the transducer. Whether or not `(mapping -)` buffers everything into memory determines whether or not it is safe to apply to an infinite sequence. Yet for the vast majority of transducers, this kind of behavior is **untested**. There needs to be a way to test this.

Inspired by RxJava, I think there should be a `materializing` transducer constructor that wraps a transducer into a transducer that emits the state transitions the original transducer performs. Proposed API:

```racket
(materializing [trans transducer?]) -> (transducer/c any/c transducer-event?)
transducer-event? : predicate/c
(define-singleton-type start-event)
(define-singleton-type half-close-event)
(define-singleton-type finish-event)
(define-wrapper-type consume-event)
(define-wrapper-type emit-event)
(define-wrapper-type half-closed-emit-event)
```

Example:

```racket
> (transduce (in-naturals) (materializing (taking 3)) #:into into-list)
(list
  start-event
  (consume-event 0)
  (emit-event 0)
  (consume-event 1)
  (emit-event 1)
  (consume-event 2)
  half-close-event
  (half-closed-emit-event 2)
  finish-event)
```

**Comment by rocketnia** [comment]
Great idea! It does sound good for unit tests like you say. Guess I oughta check out RxJava sometime.

Should `half-close-event (half-closed-emit-event 2)` be considered the same behavior as `(emit-event 2) half-close-event`? (Or is the latter ordering ill-formed? I don't quite remember the state machine.) If there are multiple representations of what ought to be thought of as the same behavior, that could be a detriment to the unit testing value.

**Comment by jackfirth** [comment]
Both of those event sequences are well formed, and they're not the same behavior. The sooner a transducer reaches the half-closed state, the faster any upstream resources can be released. For example:

```racket
(transduce (in-expensive-network-stream)
        (taking 1)
        (mapping long-cpu-intensive-computation)
        ...)
```

Here, the difference between whether `(taking 1)` does an `emit` or a `half-closed-emit` for its final value determines whether or not the resources acquired by `in-expensive-network-stream` can be released **before** calling `long-cpu-intensive-computation`. If `(taking 1)` produces a half-closed emission, then `transduce` knows it can drop the upstream sequence before passing the emitted value downstream. But if it produces a normal emission, that can't happen because `transduce` has no way of knowing that `(taking 1)` is done with the upstream sequence.

**Comment by jackfirth** [comment]
Oops, I forgot how half-closing works and that example is wrong. The `half-close-event` should only be emitted when the upstream sequence runs out of elements and the transducer is forced to half-close. So that example should actually be:

```racket
> (transduce (in-naturals) (materializing (taking 3)) #:into into-list)
(list
  start-event
  (consume-event 0)
  (emit-event 0)
  (consume-event 1)
  (emit-event 1)
  (consume-event 2)
  (half-closed-emit-event 2)
  finish-event)
```

A `taking` transducer should still use `half-closed-emit-event` for its last value since it knows it won't consume any more (and I think `taking` doesn't actually do that today!), but the `half-close-event` would only show up when the upstream sequence contains fewer values than `taking` expects:

```racket
> (transduce (list 0 1) (materializing (taking 3)) #:into into-list)
(list
  start-event
  (consume-event 0)
  (emit-event 0)
  (consume-event 1)
  (emit-event 1)
  ;; at this point, (taking 3) is trying to consume a third element but one never arrives
  half-close-event
  finish-event)
```

**Comment by rocketnia** [comment]
Thanks for explaining, and I'm glad you were able to catch this!

Those new traces look much more familiar to my preexisting understanding of the state machine. Now that I remember it better, I bet you do have a single canonical trace too.
