### ISSUE TITLE
Enum types improvements

### ISSUE THREAD

**Issue by Karrq** [jackfirth/rebellion#431]
Hello, first of all, great library!

Now I noticed some ergonomics issues around using enum types.
First, there's no easy way to export all the defined variants, in my case where I have 10+ variants it becomes tedious VERY quickly.
Second, there's a general lack of documentation around the enum data type... What does the macro provide? How does it work? 

Thanks again!

**Comment by jackfirth** [comment]
An `enum-out` feature is definitely needed, I've felt the pain from that too. Requires compile-time information for enum types, which I haven't gotten around to implementing for any of the data type APIs yet. Tracking that in #179.

**Comment by jackfirth** [comment]
Made some progress on this yesterday but haven't finished it.

**Comment by jackfirth** [comment]
This ought to be mostly fixed now, I've documented everything provided by the enum type modules.
