### ISSUE TITLE
multiset=? would be a nice addition.

### ISSUE THREAD

**Issue by jasonhemann** [jackfirth/rebellion#481]
I think I would like to have a multiset=? By analogy with set=? https://docs.racket-lang.org/reference/sets.html#%28def._%28%28lib._racket%2Fset..rkt%29._set~3d~3f%29%29 

Is that just me?

**Comment by jackfirth** [comment]
Does `equal?` work for your use case? Multisets implement `gen:equal+hash`, so using `equal?` to compare two multisets should work as expected.

**Comment by jasonhemann** [comment]
That will /precisely/ match my use case, thank you very much!
